version: "3"

dotenv:
  - .env

includes:
  db:
    taskfile: ./internal/db/taskfile.yml
    dir: ./internal/db
  docker:
    taskfile: ./docker/taskfile.yml
    dir: ./docker
  app:
    taskfile: ./internal/app/taskfile.yml
    flatten: true