version: "3"

dotenv:
  - .env

includes:
  db:
    taskfile: ./internal/db/taskfile.yml
    dir: ./internal/db
  docker:
    taskfile: ./docker/taskfile.yml
    dir: ./docker
  app:
    taskfile: ./internal/app/taskfile.yml
    flatten: true

tasks:
  rename:
    desc: Rename the Go module
    requires:
      vars: [MODULE]
    vars:
      MODULE: "{{.MODULE}}"
    cmds:
      - go mod edit -module {{.MODULE}}
      - perl -pi -e 's|go_api_template|{{.MODULE}}|g' $(find . -name "*")
      - go mod tidy
