// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type User struct {
	ID        int64
	Xid       string
	Username  string
	Email     string
	FirstName string
	LastName  string
	BirthDate *time.Time
	CreatedAt time.Time
}
