// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (xid, username, email, first_name, last_name, birth_date, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, xid, username, email, first_name, last_name, birth_date, created_at
`

type CreateUserParams struct {
	Xid       string
	Username  string
	Email     string
	FirstName string
	LastName  string
	BirthDate *time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Xid,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Xid,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, xid, username, email, first_name, last_name, birth_date, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Xid,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, xid, username, email, first_name, last_name, birth_date, created_at
FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Xid,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
