# version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: dbApi-psql
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - dbApi_data:/var/lib/postgresql

  valkey:
    image: valkey/valkey
    container_name: dbApi-valkey
    restart: unless-stopped

    ports:
      - "${CACHE_PORT:-6379}:6379"

    volumes:
      - dbApi_valkey:/data

    command: valkey-server --save 60 1 --loglevel warning

volumes:
  dbApi_data:
  dbApi_valkey: