version: "3"

vars:
  DB_URL: postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode={{.DB_SSLMODE}}

includes:
  sqlc:
    taskfile: ./sqlc/taskfile.yml

tasks:
  migrate:up:
    cmds:
      - goose -dir ./migrations postgres "{{.DB_URL}}" up

  migrate:down:
    cmds:
      - goose -dir ./migrations postgres "{{.DB_URL}}" down

  migrate:status:
    cmds:
      - goose -dir ./migrations postgres "{{.DB_URL}}" status

  migrate:create:
    desc: Create a new migration
    requires:
      vars: [NAME]
    vars:
      TYPE: '{{default "sql" .TYPE}}'
    cmds:
      - goose -dir ./migrations create {{.NAME}} {{.TYPE}}